name: Lint Check
permissions:
  contents: read
  pull_request: write
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
      - uses: pnpm/setup@v1
        with:
          version: 12
          runtime: node@24
          cache: true
      - run: pn sync 
      - run: pn lint
